# Generated by Django 5.0.1 on 2024-01-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('native_to', models.TimeField(max_length=300)),
                ('natural_habitat', models.TextField(max_length=300)),
                ('venom_level', models.CharField(max_length=100)),
                ('endangered', models.BooleanField()),
            ],
        ),
    ]
