# Generated by Django 5.0.1 on 2024-01-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='native_to',
            field=models.TextField(max_length=300),
        ),
    ]
